# docker-compose.yml
version: '3.8'

services:
  bpmn-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./logs:/app/logs